# Generated by Django 5.1.2 on 2024-12-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_actionlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
